name: "ContributorSpec"
on: [pull_request]
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build Project
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package.lock.json') }}
      - run: npm i
      - run: NEW_USER=$(git show main:contributors.json | jq -r --argjson new "$(cat contributors.json)" '. | keys - ($new | keys) | join(",")') npm run test
      - if: always()
        env:
          CONTEXT: ${{ toJSON(github) }}
        run: echo $CONTEXT > data.json
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: ${{ github.run_id }} 
          path: ./data.json
