name: ContributorSpecFailure
on: 
  workflow_run:
    workflows:
      # - ContributorSpec
      - greet-contributor-action
    types:
       - completed
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Print github context
        env:
          CHECK: ${{ github.event.workflow_run.conclusion == 'failure' }}
          CONTEXT: ${{ toJSON(github) }}
          VALUE: ${{ github.event.workflow_run.conclusion }}
        run: echo "$CHECK" && echo $VALUE && echo $CONTEXT
      - if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            It looks like you haven't order the JSON values in **ascending order alphabetically ignoring case** by Github user name or your JSON syntax is wrong. Please read the issue description before taking them.

            If you know about nodejs run the following command to sort the list:
            ```sh
              npx sort-json contributors.json --ignore-case
            ```

            **If you don't know about node js, go the following link:**
            https://codeshack.io/json-sorter/
            Paste the content of the file and generate a sorted JSON. After the paste the sorted list in the file and make a commit.


            Once this is done, your PR will be reviewed and merged.


            If you still have problem you can tag in a maintainer: @subeshb1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          allow-repeats: true
